# Generated by Django 5.0.6 on 2024-05-26 12:40

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
